name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run:  echo ${{secrets.CR_PAT}} | docker login ghcr.io -u ldraney --password-stdin

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: pizza
        run: pwd && ls -al

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/ldraney/az-trial-app:latest
            ghcr.io/ldraney/az-trial-app:${{ github.sha }}
          context: ./app
          
      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io
